### ISSUE TITLE
Check Network Connection error when adding BBC Sounds (C..E..)

### ISSUE THREAD

**Issue by ejmichel** [public-broadcasting/bbc-sounds-community-edition-for-sonos#1]
![sonos bbc sounds error](https://user-images.githubusercontent.com/16626775/226762746-a7143c52-0151-4142-8a4b-9c83da47558d.JPG)

Image above from Windows Sonos app 

also got a similar message on my iPhone Sonos App 

will triple check my settings 
but please reply if there is a resolution 

i am bereft at losing BBC on Sonos and looking forward to your solution. 

EJM

**Comment by ejmichel** [comment]
I redid the settings webpage and i must have missed something because it worked after doing that

THANKS SO MUCH FOR DOING THIS!!!!!  ejm

**Comment by public-broadcasting** [comment]
Glad to hear that it worked out in the end. Enjoy!
